### ISSUE TITLE
Create lobby button does nothing

### ISSUE THREAD

**Issue by RaysandraRexxia** [awsker/Bingus#1]
I'm connected to the server and can open the "create lobby" screen. When I click "ok," the create lobby window closes and nothing happens.

**Comment by awsker** [comment]
Do you still have this problem? Can you gather more info?

**Comment by RaysandraRexxia** [comment]
Yes I still have this problem. How do I gather more info?

**Comment by awsker** [comment]
Good question. I guess the easiest way would be if I built a custom version that prints some debug information to the console. It will probably be more efficient to try and debug this in a text chat on discord, if that's okay? My username is .asker, so add me and send a message when you have time.

**Comment by RaysandraRexxia** [comment]
Sent a friend request on Discord

**Comment by awsker** [comment]
Port being used to host the server was in use by a Windows service. Closed.
